# Generated by Django 2.2.9 on 2020-01-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200116_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilePicture',
            field=models.FileField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
