# Generated by Django 2.2.9 on 2020-01-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_userprofile_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profilePicture',
            field=models.FileField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
